name: Build Test
env:
  SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

on:
  pull_request:
    branches:
      - 'main'
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: "Deploy Production"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        if: success()
        name: checkout code

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 7
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Type Check
        run: pnpm type-check

      - name: Build
        run: pnpm build
